"""Songs table

Revision ID: 319a465e292c
Revises: 
Create Date: 2018-04-17 23:51:09.070088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319a465e292c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('lyrics', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_lyrics'), 'song', ['lyrics'], unique=False)
    op.create_index(op.f('ix_song_title'), 'song', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_title'), table_name='song')
    op.drop_index(op.f('ix_song_lyrics'), table_name='song')
    op.drop_table('song')
    # ### end Alembic commands ###
