"""added yt link

Revision ID: 3a153c3c9420
Revises: 319a465e292c
Create Date: 2018-05-08 00:05:42.777792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a153c3c9420'
down_revision = '319a465e292c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('link', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'link')
    # ### end Alembic commands ###
