"""Added latest slides

Revision ID: 9e28aac66bed
Revises: 2c5dac742a8e
Create Date: 2018-05-10 00:28:07.833008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e28aac66bed'
down_revision = '2c5dac742a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('latest_slides', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'latest_slides')
    # ### end Alembic commands ###
